module.exports = [
    {name: "Nicolas Feuillatte", prix: 30, description: "Champagne brut réserve", categorie: "champagnes", img: "https://www.sweetset.paris/285-home_default/nicolas-feuillatte.jpg"},
    {name: "Ayala", prix: 35, description: "Champagne brut réserve", categorie: "champagnes", img: "https://www.sweetset.paris/340-home_default/ayala.jpg"},
    {name: "Moët et Chandon", prix: 42, description: "Champagne brut", categorie: "champagnes", img: "https://www.sweetset.paris/374-home_default/moet-et-chandon.jpg"},
    {name: "Pommery Springtime", prix: 41, description: "Champagne rosé", categorie: "champagnes", img: "https://www.sweetset.paris/383-home_default/pommery.jpg"},
    {name: "Pommery Brut Silver", prix: 46 , description: "Champagne brut", categorie: "champagnes", img: "https://www.sweetset.paris/288-home_default/laurent-perrier-brut.jpg"},
    {name: "Nicolas Feuillatte Grand Cru 2006", prix: 41, description: "Champagne blanc de noirs", categorie: "champagnes", img: "https://www.sweetset.paris/286-home_default/gosset.jpg"},
    {name: "Ruinart", prix: 44, description: "Champagne brut", categorie: "champagnes", img: "https://www.sweetset.paris/386-home_default/ruinart.jpg"},
    {name: "Meringues Framboise", prix: 8, description: "Etui de 80g", categorie: "sweets", ss_cat: "sucré", img: "https://www.sweetset.paris/227-home_default/la-vie-en-rose-.jpg"},
    {name: "Les Biscuits Roses", prix: 6, description: "Etui de 100g", categorie: "sweets", ss_cat: "sucré", img: "https://www.sweetset.paris/228-home_default/les-biscuits-roses.jpg"},
    {name: "Salé de Reims", prix: 6, description: "Etui de 100g", categorie: "sweets", ss_cat: "salé", img: "https://www.sweetset.paris/333-home_default/grillez-moi.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Take it outside", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/329-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Truth or flare", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/328-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Vernis magnétique", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/330-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Vernis magnétique", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/331-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Vernis magnétique", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/332-home_default/vernis-essie.jpg"},
    {name: "Chardonnay", prix: 8, description: "Comte de Grignan, Année 2014", categorie: "vins", ss_cat: "vins blancs", img: "https://www.sweetset.paris/371-home_default/jurancon.jpg"},
    {name: "Pouilly Fumé", prix: 17, description: "Le Grand Plateau, Année 2013", categorie: "vins", ss_cat: "vins blancs", img: "https://www.sweetset.paris/384-home_default/pouilly-fume.jpg"},
    {name: "Pinot gris", prix: 10, description: "Jux, Année 2013", categorie: "vins", ss_cat: "vins blancs", img: "https://www.sweetset.paris/382-home_default/pinot-gris-sec.jpg"},
    {name: "Saumur Champigny", prix: 9, description: "Domaine Mollay, Année 2013", categorie: "vins", ss_cat: "vins rouges", img: "https://www.sweetset.paris/235-home_default/saumur-champigny.jpg"},
    {name: "Châteauneuf du Pape", prix: 39, description: "Année 2013", categorie: "vins", ss_cat: "vins rouges", img: "https://www.sweetset.paris/372-home_default/mont-redon-chateauneuf-du-pape.jpg"},
    {name: "Mouton Cadet", prix: 24, description: "Bordeaux, Année 2012", categorie: "vins", ss_cat: "vins rouges", img: "https://www.sweetset.paris/380-home_default/mouton-cadet.jpg"},
    {name: "Nikka 10 ans", prix: 42, description: "Whisky Japonais", categorie: "whisky", img: "https://www.sweetset.paris/276-home_default/whisky-japonais-nikka-.jpg"},
    {name: "Glenfiddich 12 ans", prix: 36, description: "Whisky Ecossais", categorie: "whisky", img: "https://www.sweetset.paris/376-home_default/glenffidich-12-ans.jpg"},
    {name: "Jack Daniels", prix: 27, description: "Whisky Américain; Bourbon", categorie: "whisky", img: "https://www.sweetset.paris/377-home_default/jack-daniels.jpg"},
    {name: "Armorik Classic", prix: 32, description: "Whisky Breton", categorie: "whisky", img: "https://www.sweetset.paris/370-home_default/armorik-classic.jpg"},
    {name: "YUMMY YUMMY", prix: 30, description: "1 côte du Rhône + 1 Pinot gris + 1 sweet meringues framboise", categorie: "chillout", img: "https://www.sweetset.paris/342-home_default/yummy-yummy-.jpg"},
    {name: "RED OR WHITE ? BOTH !", prix: 35, description: "1 Girondas rouge + 1 Pouilly Fumé", categorie: "chillout", img: "https://www.sweetset.paris/345-home_default/back-or-white-both-.jpg"},
    {name: "#75 SEPT CINQ!", prix: 56, description: "1 Monbazilla + 1 Saumur Champigny + 1 Alaya Brut", categorie: "chillout", img: "https://www.sweetset.paris/352-home_default/jackpot-777-.jpg"},
    {name: "HAPPY BIRTHDAY", prix: 36, description: "1 Nicolas Feuillatte brut réserve + 1 Sweet biscuits roses", categorie: "chillout", img: "https://www.sweetset.paris/344-home_default/happy-birthday-.jpg"},
    {name: "BRUNCHEZ-MOI", prix: 42, description: "1 Pommery brut Silve + 1 jus d'orange", categorie: "chillout", img: "https://www.sweetset.paris/347-home_default/brunchez-moi-.jpg"},
    {name: "PROMIS JE LE FERAI DEMAIN", prix: 21, description:  "1 Sancerre blanc + 1 sweet salé de Reims", categorie: "chillout", img: "https://www.sweetset.paris/359-home_default/promis-je-le-ferai-demain-.jpg"},
    {name: "SUR LES QUAIS DE PANAME", prix: 18, description: "1 rosé + 1 sweet salé de Reims", categorie: "chillout", img: "https://www.sweetset.paris/364-home_default/sur-les-quais-de-paris-.jpg"},
    {name: "VENDANGES TARDIVES", prix: 30, description: "Gewurztraminer, Vendanges tardives 2012", categorie: "ephemeres", img: "https://www.sweetset.paris/394-home_default/cotes-de-provence.jpg"},
    {name: "TORRA DI SERENA", prix: 15, description: "Torra Di Serena", categorie: "ephemeres", img: "https://www.sweetset.paris/277-home_default/la-closerie-du-pic.jpg"},
    {name: "PESSAC LEOGNAN", prix: 31, description: "Château de cruzeau, Année 2007", categorie: "ephemeres", img: "https://www.sweetset.paris/381-home_default/pessac-leognan.jpg"},
    {name: "SAINT EMILION", prix: 31, description: "Château La Diligente, Année 2011", categorie: "ephemeres", img: "https://www.sweetset.paris/378-home_default/saint-emilion.jpg"},
    {name: "TOTE BAG ROCK'N ROSES", prix: 5, description: "Sac en tissu", categorie: "ephemeres", img: "https://www.sweetset.paris/391-home_default/la-closerie-du-pic.jpg"},
    {name: "TOTE BAG POUR LES RÊVEUSES", prix: 5, description: "Sac en tissu", categorie: "ephemeres", img: "https://www.sweetset.paris/392-home_default/la-closerie-du-pic.jpg"},
    {name: "A LOVE YOU", prix: 50, description: "1 Ruinart + 1 sweet meringues framboise", categorie: "duLove", img: "https://www.sweetset.paris/351-home_default/i-m-yours.jpg"},
    {name: "COIN-COIN", prix: 52, description: "1 Moët et Chandon + 1 sweet vernis", categorie: "duLove", img: "https://www.sweetset.paris/348-home_default/coin-coin.jpg"},
    {name: "YES WE OUI!!", prix: 46, description: "1 Nicolas Feuillatte Grand Cru 2006 + 1 sweet biscuits roses", categorie: "duLove", img: "https://www.sweetset.paris/362-home_default/say-yes-.jpg"},
    {name: "RED & SEXYYY !", prix: 21, description: "1 Saint Amour + 1 sweet vernis", categorie: "duLove", img: "https://www.sweetset.paris/360-home_default/red-sexyyy-.jpg"},
    {name: "BABY I'M LATE", prix: 21, description: "1 Sancerre blanc + 1 sweet meringues framboise", categorie: "duLove", img: "https://www.sweetset.paris/365-home_default/sweet-on-you.jpg"},
    {name: "J'ATTENDS LE PROCHAIN RDV ...", prix: 48, description: "1 Pommery Springtime rosé + 1 sweet biscuits roses", categorie: "duLove", img: "https://www.sweetset.paris/355-home_default/love-you.jpg"},
    {name: "MY SWEETY", prix: 36, description: "1 Nicolas Feuillatte brut réserve + 1 sweet salé de Reims", categorie: "duLove", img: "https://www.sweetset.paris/358-home_default/my-sweety.jpg"},
    {name: "SISTER SISTER", prix: 47, description: "1 Pommery Springtime rosé + 1 sweet biscuits roses", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/366-home_default/sweet-time.jpg"},
    {name: "BLING BLING", prix: 129, description: "1 Moët et Chandon + 1 Ruinart + 1 Pommery Springtime rosé", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/346-home_default/blin-bling-attitude.jpg"},
    {name: "ENTRE PARISIENNES", prix: 31, description: "1 Sancerre blanc + 1 Pinot gris + 1 sweet vernis", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/353-home_default/les-parisiennes-.jpg"},
    {name: "SOS SURVIVAL KIT", prix: 26, description: "1 Gewurztraminer + 1 Riesling", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/363-home_default/sos-survival-kit-.jpg"},
    {name: "LET'S PARTY TONIGHT", prix: 76, description: "1 Nicolas Feuillatte Grand Cru 2006 + 1 Nicolas Feuillatte réserve + 1 sweet salé de Reims", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/354-home_default/let-s-party-tonight-.jpg"},
    {name: "QUE DES N°10 DANS MA TEAM", prix: 52, description: "1 Nicolas Feuillatte Grand Cru 2006 + 1 sweet meringues framboise + 1 sweet salé de Reims", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/369-home_default/user-friendly.jpg"},
    {name: "MUYY MACHO!", prix: 34, description: "1 Jack Daniels + 1 sweet salé de Reims", categorie: "thisIsLaFamilia", img: "https://www.sweetset.paris/356-home_default/macho-macho-men-.jpg"},
    {name: "FOR MY BOSS", prix: 38, description: "1 Chateauneuf", categorie: "theOffice", img: "https://www.sweetset.paris/350-home_default/sur-les-quais-de-paris-.jpg"},
    {name: "THANKS", prix: 34, description: "1 Saint Emilion + 1 sweet salé de Reims", categorie: "theOffice", img: "https://www.sweetset.paris/367-home_default/thanks.jpg"},
    {name: "TU T'ES VU QUAND T'AS BU !", prix: 7, description: "2 mini bouteilles d'eau Vittel + 1 mini bouteille d'eau Badoit", categorie: "theOffice", img: "https://www.sweetset.paris/368-home_default/tu-t-es-vu-quand-t-as-bu-.jpg"},
    {name: "RTT", prix: 19, description: "1 Riesling + 1 sweet salé de Reims", categorie: "theOffice", img: "https://www.sweetset.paris/361-home_default/rtt-.jpg"},
    {name: "METRO, BOULOT & PINOT", prix: 21, description: "1 Sancerre blanc + 1 sweet salé de Reims", categorie: "theOffice", img: "https://www.sweetset.paris/357-home_default/metro-boulot-dodo.jpg"},
    {name: "CONGRATS", prix: 35, description: "1 Nicolas Feuillatte brut réserve + 1 sweet meringues framboise", categorie: "theOffice", img: "https://www.sweetset.paris/349-home_default/congrats-.jpg"},
    {name: "AU REVOIR PRESIDENT", prix: 26, description: "1 Jack Daniels", categorie: "theOffice", img: "https://www.sweetset.paris/343-home_default/au-revoir-president-.jpg"},
];