module.exports = [
    {name: "Nicolas Feuillatte", prix: 30, description: "Champagne brut réserve", categorie: "champagnes", img: "https://www.sweetset.paris/285-home_default/nicolas-feuillatte.jpg"},
    {name: "Ayala", prix: 35, description: "Champagne brut réserve", categorie: "champagnes", img: "https://www.sweetset.paris/340-home_default/ayala.jpg"},
    {name: "Moët et Chandon", prix: 42, description: "Champagne brut", categorie: "champagnes", img: "https://www.sweetset.paris/374-home_default/moet-et-chandon.jpg"},
    {name: "Pommery Springtime", prix: 41, description: "Champagne rosé", categorie: "champagnes", img: "https://www.sweetset.paris/383-home_default/pommery.jpg"},
    {name: "Pommery Brut Silver", prix: 46 , description: "Champagne brut", categorie: "champagnes", img: "https://www.sweetset.paris/288-home_default/laurent-perrier-brut.jpg"},
    {name: "Nicolas Feuillatte Grand Cru 2006", prix: 41, description: "Champagne blanc de noirs", categorie: "champagnes", img: "https://www.sweetset.paris/286-home_default/gosset.jpg"},
    {name: "Ruinart", prix: 44, description: "Champagne brut", categorie: "champagnes", img: "https://www.sweetset.paris/386-home_default/ruinart.jpg"},
    {name: "Meringues Framboise", prix: 8, description: "Etui de 80g", categorie: "sweets", ss_cat: "sucré", img: "https://www.sweetset.paris/227-home_default/la-vie-en-rose-.jpg"},
    {name: "Les Biscuits Roses", prix: 6, description: "Etui de 100g", categorie: "sweets", ss_cat: "sucré", img: "https://www.sweetset.paris/228-home_default/les-biscuits-roses.jpg"},
    {name: "Salé de Reims", prix: 6, description: "Etui de 100g", categorie: "sweets", ss_cat: "salé", img: "https://www.sweetset.paris/333-home_default/grillez-moi.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Take it outside", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/329-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Truth or flare", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/328-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Vernis magnétique", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/330-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Vernis magnétique", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/331-home_default/vernis-essie.jpg"},
    {name: "Vernis Essie", prix: 10, description: "Vernis magnétique", categorie: "sweets", ss_cat: "beauté" img: "https://www.sweetset.paris/332-home_default/vernis-essie.jpg"},
    {name: "Chardonnay", prix: 8, description: "Comte de Grignan, Année 2014", categorie: "vins", ss_cat: "vins blancs", img: "https://www.sweetset.paris/371-home_default/jurancon.jpg"},
    {name: "Pouilly Fumé", prix: 17, description: "Le Grand Plateau, Année 2013", categorie: "vins", ss_cat: "vins blancs", img: "https://www.sweetset.paris/384-home_default/pouilly-fume.jpg"},
    {name: "Pinot gris", prix: 10, description: "Jux, Année 2013", categorie: "vins", ss_cat: "vins blancs", img: "https://www.sweetset.paris/382-home_default/pinot-gris-sec.jpg"},
    {name: "Saumur Champigny", prix: 9, description: "Domaine Mollay, Année 2013", categorie: "vins", ss_cat: "vins rouges", img: "https://www.sweetset.paris/235-home_default/saumur-champigny.jpg"},
    {name: "Châteauneuf du Pape", prix: 39, description: "Année 2013", categorie: "vins", ss_cat: "vins rouges", img: "https://www.sweetset.paris/372-home_default/mont-redon-chateauneuf-du-pape.jpg"},
    {name: "Mouton Cadet", prix: 24, description: "Bordeaux, Année 2012", categorie: "vins", ss_cat: "vins rouges", img: "https://www.sweetset.paris/380-home_default/mouton-cadet.jpg"},
    {name: "Nikka 10 ans", prix: 42, description: "Whisky Japonais", categorie: "whisky", img: "https://www.sweetset.paris/276-home_default/whisky-japonais-nikka-.jpg"},
    {name: "Glenfiddich 12 ans", prix: 36, description: "Whisky Ecossais", categorie: "whisky", img: "https://www.sweetset.paris/376-home_default/glenffidich-12-ans.jpg"},
    {name: "Jack Daniels", prix: 27, description: "Whisky Américain; Bourbon", categorie: "whisky", img: "https://www.sweetset.paris/377-home_default/jack-daniels.jpg"},
    {name: "Armorik Classic", prix: 32, description: "Whisky Breton", categorie: "whisky", img: "https://www.sweetset.paris/370-home_default/armorik-classic.jpg"},
    {name: "YUMMY YUMMY", prix: 30, description: "1 côte du Rhône + 1 Pinot gris + 1 sweet meringues framboise", categorie: "chillout", img: "https://www.sweetset.paris/342-home_default/yummy-yummy-.jpg"},
    {name: "RED OR WHITE ? BOTH !", prix: 35, description: "1 Girondas rouge + 1 Pouilly Fumé", categorie: "chillout", img: "https://www.sweetset.paris/345-home_default/back-or-white-both-.jpg"},
    {name: "#75 SEPT CINQ!", prix: 56, description: "1 Monbazilla + 1 Saumur Champigny + 1 Alaya Brut", categorie: "chillout", img: "https://www.sweetset.paris/352-home_default/jackpot-777-.jpg"},
    {name: "HAPPY BIRTHDAY", prix: 36, description: "1 Nicolas Feuillatte brut réserve + 1 Sweet biscuits roses", categorie: "chillout", img: "https://www.sweetset.paris/344-home_default/happy-birthday-.jpg"},
    {name: "BRUNCHEZ-MOI", prix: 42, description: "1 Pommery brut Silve + 1 jus d'orange", categorie: "chillout", img: "https://www.sweetset.paris/347-home_default/brunchez-moi-.jpg"},
    {name: "PROMIS JE LE FERAI DEMAIN", prix: 21, description:  "1 Sancerre blanc + 1 sweet salé de Reims", categorie: "chillout", img: "https://www.sweetset.paris/359-home_default/promis-je-le-ferai-demain-.jpg"},
    {name: "SUR LES QUAIS DE PANAME", prix: 18, description: "1 rosé + 1 sweet salé de Reims", categorie: "chillout", img: "https://www.sweetset.paris/364-home_default/sur-les-quais-de-paris-.jpg"},
];